
from copy import deepcopy
from genepro.fos import FOS
from numpy.random import random as randu
from numpy.random import normal as randn
from numpy.random import choice as randc
from random import shuffle
from genepro.multitree import Multitree
from genepro.node import Node
from genepro.variation import __check_tree_meets_all_constraints, __undergo_variation_operator


def generate_offspring_fos(parent : Node, 
  crossovers : list, mutations : list, coeff_opts : list,
  donors : list, internal_nodes : list, leaf_nodes : list, fos: FOS, 
  constraints : dict={"max_tree_size": 100}) -> Node:
  """
  Generates an offspring from a given parent (possibly using a donor from the population for crossover).
  Variation operators are applied in a random order.
  The application of the variation operator is handled by `__undergo_variation_operator`

  Parameters
  ----------
  parent : Node
    the parent tree from which the offspring is generated by applying the variation operators
  crossovers : list
    list of dictionaries each specifying a type of crossover and respective hyper-parameters
  mutations : list
    list of dictionaries each specifying a type of mutation and respective hyper-parameters
  coeff_opts : list
    list of dictionaries each specifying a type of coefficient optimization and respective hyper-parameters
  donors : list
    list of Node, each representing a donor tree that can be used by crossover
  internal_nodes : list
    list of internal nodes to be used by mutation
  leaf_nodes : list
    list of internal nodes to be used by mutation
  constraints : dict, optional
    constraints the generated offspring must meet (default is {"max_size": 100})

  Returns
  -------
  Node
    the offspring after having applied the variation operators
  """
    # set the offspring to a copy (to be modified) of the parent
  offspring = deepcopy(parent)
  # create a backup for constraint violation
  backup = deepcopy(offspring)

  # apply variation operators in a random order
  all_var_ops = crossovers + mutations + coeff_opts
  random_order = np.arange(len(all_var_ops))
  # TODO not shufle but use FOS!
  shuffle(random_order)
  for i in random_order:
    var_op = all_var_ops[i]
    offspring = __undergo_variation_operator(var_op, offspring, 
      crossovers, mutations, coeff_opts,
      randc(donors), internal_nodes, leaf_nodes)
    # check offspring meets constraints, else revert to backup
    if not __check_tree_meets_all_constraints(offspring, constraints):
      # revert to backup
      offspring = deepcopy(backup)
    else:
      # update backup
      backup = deepcopy(offspring)

  return offspring